# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ca81963b992b5922594fe22cb9656a15b6167a7ed1ec4e9ca5af84ea4bd449a5d5b5161be50155e8f32397e28cf2b04a657904e603011a1a15e63e6bb33ea9

test:
  secret_key_base: f8cb9159807ddc434fb2bce13cb01dfb51bf40fbf77f22de272028e4c1b2da6e40028b9a77499f667421464fdc60560f3a43125aab4c64ebed41d87141811dbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
